<a href="https://colab.research.google.com/github/fbghkh1999/LSTM/blob/master/RNN_GoogleStockPrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Dataset import 
dataset_train = pd.read_csv('/content/Google_Stock_Price_Train.csv')
training_set = dataset_train.iloc[:,1:2].values
training_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [ ]:
#skale data into 
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)
training_set_scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [ ]:
#Train set spliting
x_train = []
y_train = []
for i in range(60, 1258):
  x_train.append(training_set_scaled[i-60:i,0])
  y_train.append(training_set_scaled[i,0])

In [ ]:
#REforming to np arrays
x_train, y_train = np.array(x_train), np.array(y_train)
#reshaping to 3d tensor
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1)) 
x_train

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        ...,
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        ...,
        [0.08034452],
        [0.08497656],
        [0.08627874]],

       [[0.09433366],
        [0.09156187],
        [0.07984225],
        ...,
        [0.08497656],
        [0.08627874],
        [0.08471612]],

       ...,

       [[0.92106928],
        [0.92438053],
        [0.93048218],
        ...,
        [0.95475854],
        [0.95204256],
        [0.95163331]],

       [[0.92438053],
        [0.93048218],
        [0.9299055 ],
        ...,
        [0.95204256],
        [0.95163331],
        [0.95725128]],

       [[0.93048218],
        [0.9299055 ],
        [0.93113327],
        ...,
        [0.95163331],
        [0.95725128],
        [0.93796041]]])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout


In [ ]:
#preparing the sequential model 
model = Sequential()

In [ ]:
#LSTM first layer  
model.add(LSTM(units=50, return_sequences=True, input_shape= (x_train.shape[1],1) ))
model.add(Dropout(0.20))
#LSTM second layer 
model.add(LSTM(units=50, return_sequences=True, input_shape= (x_train.shape[1],1) ))
model.add(Dropout(0.20))
#LSTM third layer 
model.add(LSTM(units=50, return_sequences=True, input_shape= (x_train.shape[1],1) ))
model.add(Dropout(0.20))
#LSTM forth layer 
model.add(LSTM(units=50, return_sequences=True, input_shape= (x_train.shape[1],1) ))
model.add(Dropout(0.20))

#Dense output layer
model.add(Dense(units = 1))

#compile
model.compile(optimizer='adam', loss='mean_squared_error')

#fit
model.fit(x_train, y_train, epochs=50, batch_size=32)

Epoch 1/50
38/38 [==============================] - 8s 206ms/step - loss: 0.1016
Epoch 2/50
38/38 [==============================] - 8s 213ms/step - loss: 0.0361
Epoch 3/50
38/38 [==============================] - 8s 212ms/step - loss: 0.0278
Epoch 4/50
38/38 [==============================] - 8s 212ms/step - loss: 0.0241
Epoch 5/50
38/38 [==============================] - 8s 212ms/step - loss: 0.0214
Epoch 6/50
38/38 [==============================] - 8s 213ms/step - loss: 0.0195
Epoch 7/50
38/38 [==============================] - 8s 214ms/step - loss: 0.0178
Epoch 8/50
38/38 [==============================] - 8s 215ms/step - loss: 0.0170
Epoch 9/50
38/38 [==============================] - 8s 215ms/step - loss: 0.0154
Epoch 10/50
38/38 [==============================] - 8s 214ms/step - loss: 0.0154
Epoch 11/50
38/38 [==============================] - 8s 214ms/step - loss: 0.0138
Epoch 12/50
38/38 [==============================] - 8s 215ms/step - loss: 0.0130
Epoch 13/50
38/38 [======